apiVersion: v1
kind: Service
metadata:
  name: wil-service
  namespace: dev
spec:
  selector:
    app: wil-app       # This MUST match the label in the deployment
  ports:
    - protocol: TCP
      port: 80         # The port the cluster will use to talk to the service
      targetPort: 8888 # The port the container is actually listening on